export const countries = [
  { iso: "us", name: "United States", code: "+1" },
  { iso: "gb", name: "United Kingdom", code: "+44" },
  { iso: "ca", name: "Canada", code: "+1" },
  { iso: "au", name: "Australia", code: "+61" },
  { iso: "de", name: "Germany", code: "+49" },
  { iso: "fr", name: "France", code: "+33" },
  { iso: "in", name: "India", code: "+91" },
  { iso: "mx", name: "Mexico", code: "+52" },
  { iso: "br", name: "Brazil", code: "+55" },
  { iso: "za", name: "South Africa", code: "+27" },
  { iso: "ng", name: "Nigeria", code: "+234" },
  { iso: "ph", name: "Philippines", code: "+63" },
  { iso: "id", name: "Indonesia", code: "+62" },
  { iso: "pk", name: "Pakistan", code: "+92" },
  { iso: "bd", name: "Bangladesh", code: "+880" },
  { iso: "ke", name: "Kenya", code: "+254" },
  { iso: "gh", name: "Ghana", code: "+233" },
  { iso: "ae", name: "United Arab Emirates", code: "+971" },
  { iso: "sa", name: "Saudi Arabia", code: "+966" },
  { iso: "tr", name: "Turkey", code: "+90" },
];
